apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: fortune-teller-service
  labels:
    app.kubernetes.io/part-of: fortune-teller
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: fortune-teller-service
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"
  - name: ASPNETCORE_ENVIRONMENT
    value: "k8s"
  source:
    git:
      url: https://github.com/ccheetham/Samples
      subPath: Discovery/src/Fortune-Teller-Service
      ref:
        branch: tap
